# Generated by Django 3.1.5 on 2021-01-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210110_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Заказ в обработке'), ('new', 'Новый заказ'), ('completed', 'Заказ выполнен'), ('in_ready', 'Заказ готов')], default='new', max_length=100, verbose_name='Статус заказ'),
        ),
    ]
